prim_pic = imread('new.jpg');
pic_size = size(prim_pic);
pic_rot = imrotate(prim_pic,-90);
pic_resize = imresize(prim_pic,[pic_size(1),2*pic_size(2)]);
pic_change_color = imadjust(prim_pic,[0.3,0.5],[0.8,1],1);
L = 4;
[std_vector,temp] = FaceTraining(L);
[recog_pic_rot,cnt] = FaceRecognition(pic_rot,std_vector,L);
figure;
imshow(recog_pic_rot);
%imwrite(recog_pic_rot,'C:\\Users\\HJSF\\Desktop\\Dynamic\\matlab\\PP_chapter_4\\rot.jpg');
[recog_pic_resize,cnt] = FaceRecognition(pic_resize,std_vector,L);
figure;
imshow(recog_pic_resize);
%imwrite(recog_pic_resize,'C:\\Users\\HJSF\\Desktop\\Dynamic\\matlab\\PP_chapter_4\\resize.jpg');
[recog_pic_rot,cnt] = FaceRecognition(pic_change_color,std_vector,L);
figure;
imshow(pic_change_color);
%imwrite(pic_change_color,'C:\\Users\\HJSF\\Desktop\\Dynamic\\matlab\\PP_chapter_4\\change.jpg');